[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_blog_api"
version = "0.1.0"
description = "A FastAPI API to orchestrate AI blog generation agents."
requires-python = ">=3.12" 
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-dotenv",
    "sqlmodel",
    "PyMuPDF",
    "python-multipart",
    "unstructured",
    "unstructured[all-docs]",
    "jinja2",
    # Install your library from the specified GitHub repository
    "AI-Blog-App @ git+https://github.com/edilma/AI_Blog_App.git",
]

[tool.setuptools]
packages = ["app"]